name: Build binaries (manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to build (branch, tag, or SHA)"
        required: false
        default: "master"

jobs:
  bins:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'master' }}

      - name: Install MUSL toolchain (Linux targets)
        if: runner.os == 'Linux' && (matrix.target == 'x86_64-unknown-linux-musl' || matrix.target == 'aarch64-unknown-linux-musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install cross target (if any)
        if: matrix.target
        run: rustup target add ${{ matrix.target }}

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            cargo build --release --target ${{ matrix.target }} --bin agg-speed --bin agg-tunnel
          else
            cargo build --release --bin agg-speed --bin agg-tunnel
          fi
        shell: bash

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cargo build --release --bin agg-speed --bin agg-tunnel
        shell: pwsh

      - name: Collect artifacts (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p bin
          if [ -n "${{ matrix.target }}" ]; then
            cp target/${{ matrix.target }}/release/agg-speed bin/
            cp target/${{ matrix.target }}/release/agg-tunnel bin/
          else
            cp target/release/agg-speed bin/
            cp target/release/agg-tunnel bin/
          fi
        shell: bash

      - name: Collect artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          New-Item -ItemType Directory -Path bin -Force | Out-Null
          Copy-Item .\target\release\agg-speed.exe .\bin\
          Copy-Item .\target\release\agg-tunnel.exe .\bin\
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aggligator-${{ matrix.target || matrix.os }}
          path: bin
